# Generated by Django 3.2.16 on 2023-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_feed_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user_id',
            field=models.TextField(max_length=100),
        ),
    ]
